#ifndef _MZ_HEADERS_CODEGEN_GUARD
#define _MZ_HEADERS_CODEGEN_GUARD

#include "../utils/logging.h"
#include "error.h"
#include "parser.h"

#define MAX_ASM_LEN 9999999999

typedef enum CODEGEN_OUTPUT_FORMAT {
    CODEGEN_OUTPUT_FORMAT_DEFAULT = 0,
    CODEGEN_OUTPUT_FORMAT_x86_64_AT_T_ASM,
} CODEGEN_OUTPUT_FORMAT;

// typedef enum CODEGEN_OUTPUT_TYPE {
//     CODEGEN_BYTES,
//     CODEGEN_LINE,
// } CODEGEN_OUTPUT_TYPE;

// typedef struct CodegenOutputContent {
//     char *value;
//     CODEGEN_OUTPUT_TYPE type;
// } CodegenOutputContent;

const char *CODEGEN_HEADER = "This file was generated by the MZ compiler.";

#define ret                                                                    \
    if (err.type != ERROR_NULL) {                                              \
        return err;                                                            \
    }

#define MAX_BUFFER_LENGTH 20
char number[MAX_BUFFER_LENGTH + 1];

Error codegen_program(CODEGEN_OUTPUT_FORMAT, ParsingContext *, Node *, char *);
Error codegen_program_x86_64_att_asm(ParsingContext *, Node *, FILE *);

#endif